### ISSUE TITLE
使用turn后，鼠标控制没有被turn转发，流送页面卡死

### ISSUE THREAD

**Issue by 001keed** [inveta/peer-stream#124]
设置turn服务后，鼠标事件貌似没有过turn转发，导致没有检测到的接口打开，进而使得网页崩溃画面直接卡死，请问有什么解决方法吗

**Comment by xosg** [comment]
解决了？ @001keed

**Comment by 001keed** [comment]
仔细检查了一下，发现问题跟UE官方的连接控制有关，我在蓝图里面编写了断开像素流送链接的暂停游戏并传输静态画面的代码，再次连接时，继续运行并传输当前画面，可能是暂停到启动需要时间，而鼠标的询问事件比启动块，所以没有检测到接口打开，进而停止了整个串流...，当我把这段暂停的代码删除后，像素流送就能正常运行了
