### ISSUE TITLE
公网穿透

### ISSUE THREAD

**Issue by yuanlei88** [inveta/peer-stream#128]
亲爱的朋友，您做的这个太棒了，但是我用路由映射的方式无法做到公网穿透，请您抽空帮助我谢谢。

**Comment by g0415shenw** [comment]
您好，公网穿透 可以看这个录屏（虚幻引擎像素流（公网、https、linux、多项目）（基于peer-stream））
https://www.bilibili.com/video/BV1mC4y1T7rG/

**Comment by yuanlei88** [comment]
谢谢您的回复。我已经使用虚幻里面自带的turn服务器实现了公网穿透，但是因为网速的原因，效果不太好。像素流还是最好在局域网环境使用。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月1日(周一) 晚上8:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [inveta/peer-stream] 公网穿透 (Issue #128)




 
您好，公网穿透 可以看这个录屏（虚幻引擎像素流（公网、https、linux、多项目）（基于peer-stream））
 https://www.bilibili.com/video/BV1mC4y1T7rG/
