### ISSUE TITLE
浏览器失去焦点 导致收不到键盘按键释放事件

### ISSUE THREAD

**Issue by g0415shenw** [inveta/peer-stream#149]
这个是必现的

**Comment by g0415shenw** [comment]
监听 blur 事件: 当页面失去焦点时，浏览器会触发 blur 事件。你可以监听这个事件，并在事件处理函数中重置键盘状态。例如，你可以将所有正在按下的键标记为已释放。这个方法不知道可不可行？
`window.addEventListener('blur', function() {
    // 重置所有按键的状态
    // 例如，如果你有一个追踪按键状态的对象
    resetAllKeys();
});

function resetAllKeys() {
    // 重置逻辑
}
`

**Comment by xosg** [comment]
已解决
