### ISSUE TITLE
怎么让排队进入场景的人从场景的初始点开始？

### ISSUE THREAD

**Issue by slash130** [inveta/peer-stream#155]
如题  我想让排队状态进入场景的人回到初始点的状态。目前测试下来，排队进入的人是接着之前退出用户的位置和状态开始移动。

**Comment by g0415shenw** [comment]
您好，peerstream不会关注UE程序的内容的。
不过可以建议您这么实现，或许能帮助到你：
在video事件中监听"playing"事件: 场景开始渲染时，在该事件之后才能安全发送ps.emitMessage()。
然后需要自己定义一个接口 回到初始化状态。
在UE中实现回到初始化状态。
