### ISSUE TITLE
你好 怎么实现服务器端自启动ue程序啊

### ISSUE THREAD

**Issue by wbq9224** [inveta/peer-stream#16]
如题。
ue5.03
我目前的使用流程如下：
启用像素流插件，
在编辑器偏好-播放-额外启动参数中配置-AudioMixer -PixelStreamingIP=localhost -PixelStreamingPort=8888。
打包后在exe应用的快捷方式后添加-AudioMixer -PixelStreamingIP=localhost -PixelStreamingPort=8888。
node signal.js 启动信令服务器。
打开写好的html前端，信令服务器会提示已连接。

这时只能跟官方的像素流插件一样，我手动在服务器端启动一下ue的应用程序快捷方式，我的前端才能看到。如何实现自动在websocket链接时启动ue程序呢？
是我配置时漏了哪里吗？

**Comment by xosg** [comment]
在signal.js中监听到浏览器的连接时，通过child_process模块命令行启动UE程序，为了防止启动多次，需要开启单例模式插件：https://github.com/inveta/SingleTon

**Comment by wbq9224** [comment]
感谢解答！另外还有个问题，在前端调用时，吧代码中的本机调试地址
ps.setAttribute("signal", "ws://127.0.0.1:88/hello")
改成实际的服务器ip地址后，使用https，会报This request has been blocked; this endpoint must be available over WSS.的错。
如果使用http是没问题的。
这里如果一定要用https的话，要如何解决呢，有什么解决办法吗，或者是需要改写信令服务器代码吗

**Comment by g0415shenw** [comment]
支持https不需要改写信令服务器，只需要在nodejs服务器前面，增加一个nginx来代理https即可。可以搜索关键词nginx 反向代理wss websocket 这方面资料比较多。

**Comment by xosg** [comment]
https://github.com/inveta/peer-stream/blob/main/signal-auth.js
这个文件里面是自动启动的代码 @wbq9224

**Comment by xosg** [comment]
自启动在signal-pro.js里面实现了

**Comment by tjucaokun** [comment]
> 自启动在signal-pro.js里面实现了

1.我也遇到和层主一样的问题，运行signaljs之后，只能自己开启端口88的UE应用，自启动的脚本池并没有随着网页端的启动自动启动。请问这是哪里配置的问题吗？
2.而且您说的这个signal-pro.js在哪里呢 我看当前版本的仓库里没有这个文件。
