### ISSUE TITLE
使用5.1.3版本，浏览器控制台一直有UE传出的消息打印，但像素流画面有时会不显示。

### ISSUE THREAD

**Issue by QiuQianZhui** [inveta/peer-stream#162]
您好，我下载了5.1.3版本的部署工具，前端代码安装教程中的来写，浏览器控制台一直有UE传出的消息打印，但像素流画面却一直不显示；我替换成了signal.html里的写法，像素流画面有时刷新会显示，有时刷新不会显示。

**Comment by g0415shenw** [comment]
您好，可以加下qq群，我们帮你看下什么问题。
qq群号：681464378

**Comment by QiuQianZhui** [comment]
已解决。经过测试，是启动UE实例命令中的GraphicsAdapter参数配置不对导致的。
