### ISSUE TITLE
在外网访问时，在fireFox中可以正常，但是在chrome中无法正常显示，使用的peerStream是2023年4月份左右拉的代码，需要改什么东西吗？

### ISSUE THREAD

**Issue by guoshengqin2023** [inveta/peer-stream#169]

**Comment by g0415shenw** [comment]
考虑更新下chrome的版本，如果不行的话 需要看下浏览器的报错

**Comment by guoshengqin2023** [comment]
> 考虑更新下chrome的版本，如果不行的话 需要看下浏览器的报错

Chrome使用的是最新版，最难调试的就是控制台不报错，请求几组Candidate后，前端就和信令服务器保持webSocket心跳检测，控制台也没其它信息了，但是在局域网使用Chrome是正常的，公网不行。firefox是局域网和公网都是可以的

**Comment by guoshengqin2023** [comment]
> 考虑更新下chrome的版本，如果不行的话 需要看下浏览器的报错

后边有时间把推流服务升级成最新版试试，看着变动不是很大
