### ISSUE TITLE
你好对不起打扰了关于网页方面的

### ISSUE THREAD

**Issue by NierAimer** [inveta/peer-stream#17]
我打包了一个ue4.26包启动参数 
set publicIp=%1
set streamerPort=%2
start MyGame426.exe -PixelStreamingIP=%publicIp% -PixelStreamingPort=%streamerPort% -RenderOffScreen -Unattended -ForceRes -windowed -ResX=1920 -ResY=1080 -AudioMixer -graphicsadapter=0 -AllowPixelStreamingCommands -PixelStreamingEncoderRateControl=VBR

启动的信令服务器bat
node signal.js player=77 engine=7777 token=hello limit=4

但是我不清楚访问哪个网页才可以看见画面

**Comment by xosg** [comment]
这个库只支持UE5哦，历史tag还保留了一份4.27的，4.26不支持了
![image](https://user-images.githubusercontent.com/28730445/180425959-7f6b9d66-b0d2-4ef0-976b-bbfb8532667f.png)

**Comment by NierAimer** [comment]
那关于ue4像素流的信令服务怎么重写就是有点不理解，我想从他的demo调用视频流，我是主要写cpp的能给一点思路吗
