### ISSUE TITLE
关于像素流云端部署

### ISSUE THREAD

**Issue by NierAimer** [inveta/peer-stream#19]
我使用这个demo但是 html demo跑起来没有反应，就是空白网页能解答一下吗

**Comment by NierAimer** [comment]
我也不知道这样做法对不对，我用的阿里云设置所有端口开放tcp和udp，然后就成功了我不知道要不要改singal。js的peerconnect，我也改了那里。

**Comment by xosg** [comment]
控制台有报错吗？
