### ISSUE TITLE
关于UE应用程序自动关闭

### ISSUE THREAD

**Issue by chenxiandiao** [inveta/peer-stream#27]
你好，在博客介绍中提到无人访问时经过一段时间自动关闭UE5
请问现在的库中包含这部分功能吗？
或者能提供相关的思路吗？

**Comment by xosg** [comment]
这个我们是在UE5蓝图里面写逻辑。连接全部断开后经过10分钟自动退出

**Comment by xosg** [comment]
![image](https://user-images.githubusercontent.com/28730445/211248488-debc5bfb-4d1d-4d36-be9f-3fc86708478d.png)
