### ISSUE TITLE
如何在云服务器上部署？

### ISSUE THREAD

**Issue by zhaoenhe** [inveta/peer-stream#30]
把代码上传至服务器，在服务器上打开正常，在其它电脑上打开黑屏，需要如何设置可以在公网进行使用呢？

**Comment by g0415shenw** [comment]
![)VP5DPL5N ST UF5P}3NG4A](https://user-images.githubusercontent.com/40832854/207514593-d4af52cb-ac07-4465-9564-8013c79e0793.jpg)
![3~QR~}LAU 7BP59X5L8BX6J](https://user-images.githubusercontent.com/40832854/207514613-c62f0afe-f613-4418-b2c9-5ac453b78b8c.jpg)

**Comment by g0415shenw** [comment]
将stun服务打开，就可以在公网使用了
