### ISSUE TITLE
同时维护4.27和UE5最新版本

### ISSUE THREAD

**Issue by g0415shenw** [inveta/peer-stream#37]
考虑到好多朋友都在用UE4的像素流
建议维护一套功能全面的UE4.27版本
另外UE5的话，就跟着官方版本进行迭代
@xosg 你觉得咋样

**Comment by xosg** [comment]
现在先同时维护5.0和5.1吧

**Comment by Smecta** [comment]
> 现在先同时维护5.0和5.1吧

请教一下 UE像素流那边是4.27 , 前端`peer-stream.js` 可以用最新版本吗？

**Comment by xosg** [comment]
我们已经同时支持UE4和UE5了 @Smecta
