### ISSUE TITLE
How to lock the mouse?

### ISSUE THREAD

**Issue by vamman** [inveta/peer-stream#38]
I am wondering how do I lock the mouse with peer-stream? I want to lock the mouse to the <video></video> when the player clicks into the video container. When the player wants their mouse cursor back they will need to click the Esc key. I believe this functionality already exists in Epic's original code but I can not figure out how to enable it with peer-stream. I appreciate that the work you have done here to simplify the solution. Thanks.

**Comment by xosg** [comment]
it's quite easy, just call ps.registerPointerLockEvents(); Then call ps.requestPointerLock()
