### ISSUE TITLE
iPhone无法打开peer-stream的链接

### ISSUE THREAD

**Issue by mumumomo** [inveta/peer-stream#39]
无论是旧款iPhone还是新款，似乎都无法打开。但是安卓的可以

**Comment by xosg** [comment]
由于IOS端Safari不支持自定义内置元素（customized built-in element），需要在peer-stream.js之前引入兼容包：https://github.com/ungap/custom-elements 。除此之外，IOS微信内置浏览器（小程序）禁止video自动播放，必须由用户行为触发调用ps.play()来播放视频流。

**Comment by mumumomo** [comment]
感谢！
