### ISSUE TITLE
请问如何在一台完全不联网的机器上使用流推送？

### ISSUE THREAD

**Issue by Zydiii** [inveta/peer-stream#44]
在完全不联网的机器上（不插网线，Wifi 不连），流推送会显示黑屏，看 log 是只进行到了 ↑↑ answer 这一步
![7@ B9DTWVM_HR95RLCQH~(G](https://user-images.githubusercontent.com/37077660/224523798-99fa5fd7-8547-4b6d-9071-b3eed5d1f863.png)
当我打开网络后后续的 log 立马就会出现了 ↓↓ candidate
![8X2B569E8A8RG@O5)BVHH4K](https://user-images.githubusercontent.com/37077660/224523835-3fd13d38-2958-4ad4-b8ca-7ce62a70562a.png)
我也有试过让电脑直接连接我的手机热点，但手机不开网络，流送是正常的，说明也不需要能够连接外网
我想请教一下这个问题是流送服务器的问题还是 UE 端的问题呢？如果能获得解答真的会非常感谢！

**Comment by xosg** [comment]
这是浏览器WebRTC的一个bug，必须要网口开着（插网线）才能访问，即使是localhost。

**Comment by Zydiii** [comment]
好的，谢谢！
