### ISSUE TITLE
请问是否有办法做到跟随游览器窗口变化视频界面大小

### ISSUE THREAD

**Issue by ladyishenlong** [inveta/peer-stream#45]
现在的视频流大小是固定的

**Comment by xosg** [comment]
用UE5.1，可以发送命令调节分辨率

**Comment by Episode-Zhang** [comment]
可以试着给<video is="peer-stream">元素外层套一个<div>，然后分别设置div的样式为“position: relative”，<video>元素的样式为"position: absolute; width: 100%; height:100%"，然后调整外层的div的宽高就行了，视频流的宽高会跟着外层的div变
