### ISSUE TITLE
Tried to send command or UIINteractions

### ISSUE THREAD

**Issue by MaximeM** [inveta/peer-stream#48]
Hello there,

Sending UI Interactions or commands doesnt seem to work

// Generic Input Messages. Range = 50..59.
	UIInteraction: 50,
	Command: 51,
	
	any advice?

**Comment by xosg** [comment]
for  UI Interactions, ps.emitMessage(msg: string | object); should works

**Comment by MaximeM** [comment]
yes it did sorry, I found it just now, thanks for the answer!

Do you know if we can send message from the signal to UE directly?
