### ISSUE TITLE
怎么输入中文？

### ISSUE THREAD

**Issue by zixixr** [inveta/peer-stream#51]
在PIXSEL STREAMING环境下，点击文本框，无法调动输入法，只能打英文，请问老铁们是怎么解决的

**Comment by PengChaoJay** [comment]
感觉是不是可以直接在前端html页面搞输入框，毕竟pixel streming 通过h.264 对视频进行编码，使用webrtc实现端到端的连接

**Comment by g0415shenw** [comment]
目前虚幻像素流库不支持中文数据，后续我们思考如何在peerstream里面兼容中文输入

**Comment by zixixr** [comment]
是的，我们现在就这么搞的，左下角的聊天输入都是前端做的发自我的 iPhone在 2023年6月26日，16:14，PengChaoJay ***@***.***> 写道：﻿
感觉是不是可以直接在前端html页面搞输入框，毕竟pixel streming 通过h.264 对视频进行编码，使用webrtc实现端到端的连接

**Comment by g0415shenw** [comment]
目前企业版已经支持中文，这里关闭了
