### ISSUE TITLE
limit设置后UE实例最后一个无法连入问题

### ISSUE THREAD

**Issue by zhangzhi532200** [inveta/peer-stream#52]
我设置limit = 5，one2one = true，5个用户正常连入，UE实例只能连入4个，最后一个访问的用户黑屏，缺了一个实例连接，有知道是什么问题吗

**Comment by lfqq** [comment]
我开了50个，一对一，只连进去3个，第四个死活一打开就立马关闭了

**Comment by AyzyVictorio** [comment]
你找到解决办法了吗？

**Comment by xosg** [comment]
机器带不动那么多UE实例吧，而且limit这个参数我们去掉了，不用了 @lfqq @zhangzhi532200
