### ISSUE TITLE
负载均衡启动UE逻辑感觉有点问题

### ISSUE THREAD

**Issue by g0415shenw** [inveta/peer-stream#56]
在下面的处理函数中
`PLAYER.on('connection', (fe, req) => {`
整个业务逻辑如下，这里只考虑one2one模式
当有新的client连接上来之后，会选择一个空闲的UE，即ue.fe.size === 0。
如果可以找到，就把这个UE分配给连接上来的client。
如果没有找到，就从UE5_pool中取出第一个显卡实例，然后将第二个显卡实例移动到第一个，
并将第一个显卡实例移到最后一个。

存在问题：
1、这里没有考虑一种情况，就是从UE5_pool中取出的显卡实例，如果已经开着，那么会导致开启失败。
此时这个client将不会被分配到显卡实例了。

**Comment by g0415shenw** [comment]
这个问题确实存在，有可能无法分配到显卡实例。
解决方案：
由于UE实例连接上来之后，只知道websocket的url地址，其他任何信息都获取不到。
所以要想区分出每个连接上来的实例对应于UE5_pool中的实例，我们只能通过url地址来区分。
所以决定动态的进行修改url地址，
使得这个url地址可以唯一，从而可以识别出不同的UE实例。
比如通过这种方式，通过动态增加一个实例的名称来实现识别。
ws://127.0.0.1:88/UE5_GPU_0

**Comment by g0415shenw** [comment]
配置文件参数如下
`process.env.UE5_GPU_1 = "start C:/Users/admin/Desktop/Windows/gza.exe -Unattended -RenderOffScreen -PixelStreamingURL=ws://127.0.0.1:88/ -GraphicsAdapter=0 -ProjectID=GPU_1 -AllowPixelStreamingCommands`
我们计划动态将PixelStreamingURL的值修改为
ws://127.0.0.1:88/UE5_GPU_1/

当每次有新的连接上来之后，如有没有开启的UE示例，我们会到池子里面去找没有开启的实例，找到之后再执行开启。
所以我们需要增加一个函数，在UE5_pool中寻找没有开启的UE实例。

另外，在连接上来的ue实例中，我们还需要记录下连接上来的url地址，从而进行分区。

**Comment by g0415shenw** [comment]
但是如果是跨机器的话，配置的参数如下
process.env.UE5_10_0_42_16 = 'curl http://10.0.42.16/RUN-UE5'
这一块又如何来区分么？

**Comment by xosg** [comment]
下载 PsExec（远程执行exe）：https://learn.microsoft.com/en-us/sysinternals/downloads/psexec

```js
// 本机（10.0.42.1）
process.env.UE5_GPU1 = `start  UE5.exe  -PixelStreamingURL=ws://127.0.0.1:88/UE5_GPU1`;

// GZA服务器上（10.0.42.16）
process.env.UE5_GZA1 = `psexec  \\10.0.42.16  "UE5.exe"  "-PixelStreamingURL=ws://10.0.42.1:88/UE5_GZA1"`;
```

**Comment by g0415shenw** [comment]
如下图的思路，为了解决跨机器启动ue程序的问题，决定引入一个启动层，通过websocket与signal通信，然后将之前的
process.env.UE5_GPU1 = `start  UE5.exe  -PixelStreamingURL=ws://127.0.0.1:88/UE5_GPU1`;
修改为通过websocket发送给不同的start层。所以启动方式全部统一。整个环境变量的修改如下
process.env.UE5_GPU1 = `10.0.42.16 `+`start  UE5.exe  -PixelStreamingURL=ws://127.0.0.1:88/UE5_GPU1`;
第一个为服务器的IP地址，即通过websocket连上来的地址，后面的和之前的启动参数一致。

![image](https://user-images.githubusercontent.com/40832854/234765822-03baaf2d-5972-4233-8a07-1e045874cd18.png)

**Comment by xiaobug0929** [comment]
这部分大佬们准备啥时候能上线哇

**Comment by xosg** [comment]
上线了 @xiaobug0929
