### ISSUE TITLE
新增用户排队功能

### ISSUE THREAD

**Issue by zhangzhi532200** [inveta/peer-stream#57]
用户加入后超过limit数量限制后将无法连接，用户没有得到对应的提示，体验感较差，希望能增加用户排队功能，用户在HTML页面中能看到前方需要排队的人数，排队结束后自动进入并显示画面。

**Comment by g0415shenw** [comment]
考虑增加一个排队的队列
当达到limit限制之后，将这个websocket连接丢到排队的队列中去。
如果有其他用户释放了连接，就把这个资源给队列中第一个用户。

另外还计划增加一个定时器，定时通知用户，当前前面等待的用户数量。

- [ ] 增加一个派对队列

- [ ] 当有用户释放了资源，立刻将资源分配给队列中第一个用户

- [ ] 增加一个定时器，定期通知用户当前排队的用户数量

**Comment by g0415shenw** [comment]
已经解决
