### ISSUE TITLE
部署到服务器无法使用

### ISSUE THREAD

**Issue by jeunggaaising** [inveta/peer-stream#65]
部署到服务器后UDP的链接地址访问的是服务区的Ipv4地址而不是服务器的公网ip或者服务区的127.0.0.1，导致客户端无法得到推流的影像，原因是客户端无法直接访问服务区端的ipv4

**Comment by g0415shenw** [comment]
这里需要开启stun即可，需要两个地方开启
地方一：
![image](https://github.com/inveta/peer-stream/assets/40832854/1d7fa22c-8a63-4402-984c-43d54654896f)
地方二：
![image](https://github.com/inveta/peer-stream/assets/40832854/042b1096-96f0-4f43-aaf7-abf527ff5b0c)
