### ISSUE TITLE
nodejs容器把服务器的文件完全暴露，Web服务器目录遍历任意文件访问，物理路径泄露的高风险漏洞！

### ISSUE THREAD

**Issue by zhangzhi532200** [inveta/peer-stream#76]
访问服务地址后Node会将文件路径及文件暴露在外网下（Web服务器目录遍历任意文件访问），需要把物理地址去掉避免他人知道文件位置进行攻击操作，高风险漏洞！
ENOENT: no such file or directory, open 'C:\Users\Windows\Desktop\peer-stream-main\passwd'

**Comment by xosg** [comment]
这个问题已经解决了 @zhangzhi532200 @g0415shenw
