### ISSUE TITLE
预加载的问题

### ISSUE THREAD

**Issue by g0415shenw** [inveta/peer-stream#80]
预加载目前机制如下：5秒检查一下，如果实例都被占用了，就启动一个新的实例。
存在的问题：
当UE程序文件过大，启动之后需要非常长的时间连上signal，那么就会出现每隔5秒启动一次相同的实例，从而导致磁盘占用率过大。
机器卡主。。。
假设启动一个实例需要60秒，那么我们会在1分钟以内开启12个相同的实例。

**Comment by g0415shenw** [comment]
这里决定引入一个冷却时间的配置参数，当UE启动一个实例之后，在冷却时间之内，无法再启动相同的实例，通过根据现场的UE实例的启动时间长短，来动态调整这个参数，从而解决预加载启动机器卡主的问题。

**Comment by g0415shenw** [comment]
引入冷却时间之后，又遇到一个新的问题。就是不会启动当前实例了，但是会去启动其他实例。。。如果有12个实例，每个实例启动需要60秒，那么会在60秒之内，把12个实例全部启动一遍。。。
这个也是无法接受的事情。。。

**Comment by TreeWish** [comment]
> 
我把预加载关闭，同时设置多个实例时（一般指定 8个以上的时候就会出现该问题），UE程序会疯狂开启。但是当我使用比较小的ue 测试包然后去通过打断点的方式在每次连接的时候断一下手动去运行ue程序就没有这个问题 ，推测和这预加载的这个情况一样，能否判断在加载完第一个实例之后再去加载第二个。如果有类似这种的机制应该就解决这个问题。

**Comment by g0415shenw** [comment]
这个问题已经解决了，目前引入了一个冷却时间的参数，在最新的版本，在.signal中
//启动UE实例的冷却时间
//process.env.exeUeCoolTime = 60
每个实例在一定时间内只会开启一次。
当然如果同时有8个人一起并发访问，确实会出现同时开启8个不同实例的情况。这个目前好像无法避免。
