### ISSUE TITLE
设置limit限制前端数量，websocket会拒绝连接，引起排队逻辑无效

### ISSUE THREAD

**Issue by zhangzhi532200** [inveta/peer-stream#89]
设置limit限制前端数量，websocket会拒绝连接，
// players max count
    if (process.env.limit) {
      if (PLAYER.clients.size >= process.env.limit) {
        socket.destroy()
        return
      }
    }
排队逻辑无效，是否可以在配置limit前端限制数量时，不拒绝websocket的连接

**Comment by g0415shenw** [comment]
已经去掉了limit的功能，通过UE的实例配置，来进行数量限制。
