### ISSUE TITLE
怎么使用一个服务管理多个不同的Ue

### ISSUE THREAD

**Issue by jak983464779** [inveta/peer-stream#90]
我有多个不同的ue 程序，怎么让前端连接指定ue程序的像素流

**Comment by g0415shenw** [comment]
目前还不行，需要开启多个signal来进行设置。
另外还有一种思路，通过websocket的url地址的不同进行区分不同的，在前面增加一个nginx。这样对外端口可以同一个。
后端还是需要开启多个不同的signal服务。

**Comment by jak983464779** [comment]
后续有计划把这个功能加上吗？

**Comment by g0415shenw** [comment]
建议在前面增加一个nginx来解决这个问题，开启多个signal，这个项目不准备来管理了。
