### ISSUE TITLE
开启像素流后，服务器端口一直连续增加的问题

### ISSUE THREAD

**Issue by Freedomeri** [inveta/peer-stream#94]
![屏幕截图 2023-07-28 111226](https://github.com/inveta/peer-stream/assets/32265027/de244452-ee66-4cd3-9a3c-a2b6f8062210)
如图，在只开启信令服务器时，正常；

但在浏览器访问像素流页面的时候，端口就开始不断自动增加：
![屏幕截图 2023-07-28 111545](https://github.com/inveta/peer-stream/assets/32265027/19b0beab-64e4-434a-af2d-d914abc52b9c)
![屏幕截图 2023-07-28 111601](https://github.com/inveta/peer-stream/assets/32265027/3f740696-290c-4ae3-8cb4-ba69aff0d92f)

在执行一些小项目的时候并没出现这个问题，这次执行的是一个比较大的UE可执行文件。不知是否是哪部分配置需要修改？

**Comment by g0415shenw** [comment]
可以把配置发一下，我们看下 ，配置文件是.signal文件。感觉是UE进程挂了，然后有开起来了。所以端口才会不停的变化。

**Comment by Freedomeri** [comment]
> 可以把配置发一下，我们看下 ，配置文件是.signal文件。感觉是UE进程挂了，然后有开起来了。所以端口才会不停的变化。

谢谢！文件如下：
// require('child_process').exec(`start http://localhost:88/test.html`);

// 设置环境变量

// 唯一端口号
process.env.PORT = 88;

// process.env.token = "/test.html";
process.env.limit = 4;
process.env.throttle = true;

// 一对一
process.env.one2one = true;

// 自启动脚本池，以"UE5_"开头
process.env.UE5_GPU_0 = "start D:/0UEProjects/EXE/WindowsNoEditor/VoskHost.exe -Unattended -RenderOffScreen -PixelStreamingURL=ws://127.0.0.1:88/ -GraphicsAdapter=0 -ProjectID=GPU_0 -ForceRes -ResX=1920 -ResY=1080 -AllowPixelStreamingCommands";
process.env.UE5_GPU_1 = "start D:/0UEProjects/EXE/WindowsNoEditor/VoskHost.exe -Unattended -RenderOffScreen -PixelStreamingURL=ws://127.0.0.1:88/ -GraphicsAdapter=0 -ProjectID=GPU_1 -AllowPixelStreamingCommands";
process.env.UE5_GPU_2 = "start D:/0UEProjects/EXE/WindowsNoEditor/VoskHost.exe -Unattended -RenderOffScreen -PixelStreamingURL=ws://127.0.0.1:88/ -GraphicsAdapter=0 -ProjectID=GPU_2 -AllowPixelStreamingCommands";

// 预加载1个空闲的UE5进程
// process.env.preload = 1;

// process.env.UE5_10_0_42_16 = 'curl http://10.0.42.16/RUN-UE5'

require("./signal.js");

**Comment by g0415shenw** [comment]
看上去一切正常，感觉需要远程上去看下，可以加我qq:411320557 我们看下

**Comment by Freedomeri** [comment]
> 看上去一切正常，感觉需要远程上去看下，可以加我qq:411320557 我们看下

谢谢您，已经找到问题了，最新版peer-stream会在前端发送含有"type" = "playerConnected"的JSON消息，但是我启动的是4.27版本的ue程序......识别不了。换成4.27版的peer-stream就好了~

顺便问一下，4.27版本的插件，启动像素流之后在网页端应该怎么访问到html文件呀？我尝试过用令牌"ip:88?token=hello"，并没有反应...

**Comment by g0415shenw** [comment]
4.27好多功能没有，并不是一个完整的版本，好几年前开发的。

**Comment by g0415shenw** [comment]
您好，最新版已经支持4.27了，可以直接使用

**Comment by Freedomeri** [comment]
> 您好，最新版已经支持4.27了，可以直接使用

谢谢，辛苦了
